version: 'version'
services:
  # database layer for wordpress >> MYSQL DB
  mysql_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_dp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
     # wordpress on apache
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:6.0-php8.1-apache
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_dp
    volumes: [ "./:/var/www/html" ]
     # phpmyadmin to display data
  phpmyadmin:
    depends_on: 
     - mysql_database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment: 
     PMA_HOST: mysql_database
     MYSQL_ROOT_PASSWORD: 1234
volumes:
 mysql: {}
